### ISSUE TITLE
Will you plan to support .NET standard?

### ISSUE THREAD

**Issue by xBoo** [BrightOpen/log4net.Ext.Json#1]
I want to use this SDK in .NET core, but it dose not support .Net Standard library, so will you plan to update 
this for support .NET standard?

**Comment by jocutajar** [comment]
Hi, I'm undecided about this. It would take a good while till I get to it. I think the project needs a refresh and update in any case.

**Comment by jocutajar** [comment]
Yp, done in 2.0.8.* Kind regards, Rob
